### ISSUE TITLE
Link checker does not work due to certificate issues

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/doc-it#574]
Whether I `go home` or `go work`, when I try to `yarn check:links` locally, all I got was errors. There are no severe consequences but we have to rely on CI to check everything.

```
  8 links checked.

  ERROR: 7 dead links found!
  [✖] https://material.io/ → Status: 0
  [✖] https://github.com/brightlayer-ui → Status: 0
  [✖] https://github.com/angular/angular/issues → Status: 0
  [✖] https://github.com/angular/material2/issues → Status: 0
  [✖] https://github.com/facebook/react/issues → Status: 0
  [✖] https://github.com/mui-org/material-ui/issues → Status: 0
  [✖] https://github.com/facebook/react-native/issues → Status: 0

FILE: src/docs/community/our-team.mdx
  [✖] https://www.designinnovationglobal.com/design-thinking/articles/di-global-awards-winners → Status: 0 Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```

**Comment by jeffvg** [comment]
I ran link checker on my local and didn't see any certificate errors related to this bug. However locally I did receive dead link for this but the site does have about 30 403's for resources didn't load but the site opens..

https://www.adobe.com/products/illustrator.html

<img width="655" alt="image" src="https://user-images.githubusercontent.com/37150565/182616022-ef297da8-aeeb-447e-a4e3-b9a910f1f56b.png">

**Comment by huayunh** [comment]
That one should have been "fixed" now with the new branch merge — I ended up having to disable the link checker for that link.

**Comment by bkarambe** [comment]
This issue still exists in dev .
<img width="1140" alt="Screenshot 2022-12-21 at 12 27 50 PM" src="https://user-images.githubusercontent.com/25982779/208841158-c87ca0cf-6640-43a9-9a56-307da2270156.png">
